version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: french_quiz_backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:cached
    environment:
      - PYTHONUNBUFFERED=1

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: french_quiz_bot
    ports:
      - "8090:8090"
    volumes:
      - ./:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
